/*
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
 */
package com.wikantik.knowledge.querylog;

import com.wikantik.api.querylog.ActorType;
import com.wikantik.api.querylog.SourceSurface;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.Executor;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class JdbcQueryLogServiceTest {

    /** Same-thread executor so the fire-and-forget write is deterministic in tests. */
    private static final Executor INLINE = Runnable::run;

    private DataSource ds;

    @BeforeEach
    void setUp() throws Exception {
        final JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL( "jdbc:h2:mem:qlog;MODE=PostgreSQL;DB_CLOSE_DELAY=-1" );
        this.ds = h2;
        try ( Connection c = ds.getConnection(); Statement s = c.createStatement() ) {
            s.executeUpdate( "DROP TABLE IF EXISTS retrieval_query_log" );
            s.executeUpdate( """
                CREATE TABLE retrieval_query_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    query_text TEXT NOT NULL,
                    actor_type VARCHAR(16) NOT NULL,
                    source_surface VARCHAR(32) NOT NULL,
                    result_count INTEGER,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )""" );
        }
    }

    private int count() throws SQLException {
        try ( Connection c = ds.getConnection(); Statement s = c.createStatement();
              ResultSet rs = s.executeQuery( "SELECT count(*) FROM retrieval_query_log" ) ) {
            rs.next();
            return rs.getInt( 1 );
        }
    }

    @Test
    void log_insertsRowWithAllFields_whenEnabled() throws Exception {
        new JdbcQueryLogService( ds, true, INLINE )
            .log( "how do I deploy locally", ActorType.HUMAN, SourceSurface.API_BUNDLE, 5 );

        try ( Connection c = ds.getConnection(); Statement s = c.createStatement();
              ResultSet rs = s.executeQuery(
                  "SELECT query_text, actor_type, source_surface, result_count FROM retrieval_query_log" ) ) {
            assertTrue( rs.next(), "a row was written" );
            assertEquals( "how do I deploy locally", rs.getString( "query_text" ) );
            assertEquals( "human", rs.getString( "actor_type" ) );
            assertEquals( "api_bundle", rs.getString( "source_surface" ) );
            assertEquals( 5, rs.getInt( "result_count" ) );
        }
    }

    @Test
    void log_isNoOp_whenDisabled() throws Exception {
        new JdbcQueryLogService( ds, false, INLINE )
            .log( "q", ActorType.AGENT, SourceSurface.API_SEARCH, 3 );
        assertEquals( 0, count() );
    }

    @Test
    void log_skipsBlankOrNullQuery() throws Exception {
        final JdbcQueryLogService svc = new JdbcQueryLogService( ds, true, INLINE );
        svc.log( "   ", ActorType.HUMAN, SourceSurface.API_BUNDLE, 1 );
        svc.log( null, ActorType.HUMAN, SourceSurface.API_BUNDLE, 1 );
        assertEquals( 0, count(), "blank/null query text is not logged" );
    }

    @Test
    void log_storesNullResultCount() throws Exception {
        new JdbcQueryLogService( ds, true, INLINE )
            .log( "q", ActorType.AGENT, SourceSurface.MCP_ASSEMBLE_BUNDLE, null );
        try ( Connection c = ds.getConnection(); Statement s = c.createStatement();
              ResultSet rs = s.executeQuery( "SELECT result_count FROM retrieval_query_log" ) ) {
            assertTrue( rs.next() );
            rs.getInt( "result_count" );
            assertTrue( rs.wasNull(), "null result_count is stored as SQL NULL" );
        }
    }

    @Test
    void log_failsOpen_onSqlError() throws Exception {
        final DataSource broken = mock( DataSource.class );
        when( broken.getConnection() ).thenThrow( new SQLException( "no connection" ) );
        assertDoesNotThrow( () -> new JdbcQueryLogService( broken, true, INLINE )
            .log( "q", ActorType.HUMAN, SourceSurface.API_BUNDLE, 1 ),
            "a write failure must never propagate to the retrieval path" );
    }
}
