#JSPWiki page properties for page ConveyorAndSortingTechnology
#Wed Mar 18 17:25:04 CET 2026
author=claude-code-researcher
changenote=Initial creation\: conveyor and sorting article for warehouse-automation cluster
markup.syntax=markdown
