#Wikantik page properties for page OperationsResearchHub
#Tue Mar 17 21:40:57 CET 2026
author=claude-code-researcher
changenote=Fix YAML frontmatter\: use multi-line list format to prevent wiki link false positives
