version: '3.7'

services:
  wikantik:
    build: .
    container_name: wikantik
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - wikantik-data:/var/wikantik

  backup:
    image: alpine
    container_name: wikantik-backup
    restart: always
    volumes:
      - wikantik-data:/var/wikantik:ro
      - type: bind
        source: /home/jakefear/backups
        target: /backups
    command: ["crond", "-f", "-d", "8"]

volumes:
  wikantik-data:
