/*
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
 */
package com.wikantik.rest;

import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.FilterConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Adds an {@code X-Build-Version} response header to every request, allowing
 * the SPA to detect when the server has been redeployed with a new build.
 *
 * <p>The version is read once at init from {@code /build-version.txt} in the
 * WAR root (generated by the Vite build plugin). If the file is missing,
 * no header is set.
 */
public class BuildVersionFilter implements Filter {

    private static final Logger LOG = LogManager.getLogger( BuildVersionFilter.class );

    private String buildVersion;

    @Override
    public void init( final FilterConfig config ) throws ServletException {
        try ( InputStream in = config.getServletContext().getResourceAsStream( "/build-version.txt" ) ) {
            if ( in != null ) {
                buildVersion = new String( in.readAllBytes(), StandardCharsets.UTF_8 ).trim();
                LOG.info( "Build version: {}", buildVersion );
            } else {
                LOG.warn( "build-version.txt not found — X-Build-Version header will not be set" );
            }
        } catch ( final IOException e ) {
            LOG.warn( "Failed to read build-version.txt", e );
        }
    }

    @Override
    public void doFilter( final ServletRequest request, final ServletResponse response,
                           final FilterChain chain ) throws IOException, ServletException {
        if ( buildVersion != null ) {
            ( ( HttpServletResponse ) response ).setHeader( "X-Build-Version", buildVersion );
        }
        chain.doFilter( request, response );
    }

    @Override
    public void destroy() {
    }
}
