/*
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
 */
package com.wikantik.auth;

import com.wikantik.HsqlDbUtils;
import com.wikantik.TestEngine;
import com.wikantik.TestJDBCDataSource;
import com.wikantik.TestJNDIContext;
import com.wikantik.api.core.Session;
import com.wikantik.auth.authorize.Role;
import com.wikantik.auth.permissions.AllPermission;
import com.wikantik.auth.permissions.PagePermission;
import com.wikantik.auth.permissions.WikiPermission;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NameAlreadyBoundException;
import javax.sql.DataSource;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Properties;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for {@link DatabasePolicy}, which loads policy grants from the
 * {@code policy_grants} database table and provides an
 * {@code implies(Principal, Permission)} method.
 */
@TestInstance( TestInstance.Lifecycle.PER_CLASS )
class DatabasePolicyTest
{
    private final HsqlDbUtils hu = new HsqlDbUtils();
    private DataSource ds;
    private DatabasePolicy policy;

    @BeforeAll
    void startDatabase() throws Exception
    {
        hu.setUp();

        // Set up the mock JNDI initial context
        TestJNDIContext.initialize();
        final Context initCtx = new InitialContext();
        try
        {
            initCtx.bind( "java:comp/env", new TestJNDIContext() );
        }
        catch( final NameAlreadyBoundException e )
        {
            // ignore -- already bound by another test
        }
        final Context ctx = (Context) initCtx.lookup( "java:comp/env" );
        ds = new TestJDBCDataSource( new File( "target/test-classes/wikantik-custom.properties" ), hu.getDriverUrl() );
        ctx.bind( "jdbc/PolicyDatabase", ds );

        // Create policy_grants table using admin connection (SA user has DDL privileges)
        try( final Connection adminConn = DriverManager.getConnection( hu.getDriverUrl(), "SA", "" );
             final Statement stmt = adminConn.createStatement() )
        {
            stmt.executeUpdate(
                "CREATE TABLE IF NOT EXISTS policy_grants (" +
                "  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  principal_type VARCHAR(10) NOT NULL," +
                "  principal_name VARCHAR(255) NOT NULL," +
                "  permission_type VARCHAR(10) NOT NULL," +
                "  target VARCHAR(255) NOT NULL," +
                "  actions VARCHAR(255) NOT NULL" +
                ")"
            );
            stmt.executeUpdate( "GRANT SELECT, INSERT, UPDATE, DELETE ON policy_grants TO \"wikantik\"" );
        }
    }

    @BeforeEach
    void setUp() throws Exception
    {
        try( final Connection conn = ds.getConnection();
             final Statement stmt = conn.createStatement() )
        {
            // Reset data using DML (the wikantik user has DML privileges)
            stmt.executeUpdate( "DELETE FROM policy_grants" );

            // Seed data matching the default wiki policy
            // All role: view only
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'All', 'page', '*', 'view')"
            );
            // Anonymous role: login, editProfile
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Anonymous', 'wiki', '*', 'login,editProfile')"
            );
            // Authenticated role: page modify,rename
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Authenticated', 'page', '*', 'modify,rename')"
            );
            // Authenticated role: wiki createPages,createGroups
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Authenticated', 'wiki', '*', 'createPages,createGroups')"
            );
            // Authenticated role: group edit on <groupmember>
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Authenticated', 'group', '*:<groupmember>', 'edit')"
            );
            // Admin role: AllPermission (actions = '*')
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Admin', 'page', '*', '*')"
            );
        }

        // Create a fresh policy instance that reads from the seeded table
        policy = new DatabasePolicy( ds, "policy_grants" );
    }

    @AfterAll
    void stopDatabase()
    {
        hu.tearDown();
    }

    // ---- Test methods ----

    @Test
    void testAuthenticatedRoleHasModifyPermission()
    {
        assertTrue(
            policy.implies( Role.AUTHENTICATED, new PagePermission( "*:*", "modify" ) ),
            "Authenticated role should have modify permission on all pages"
        );
    }

    @Test
    void testAuthenticatedRoleHasViewViaImplication()
    {
        // modify implies view (modify -> edit -> view)
        assertTrue(
            policy.implies( Role.AUTHENTICATED, new PagePermission( "*:*", "view" ) ),
            "Authenticated role should have view permission via modify implication"
        );
    }

    @Test
    void testAnonymousRoleLacksDeletePermission()
    {
        assertFalse(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "delete" ) ),
            "Anonymous role should NOT have delete permission"
        );
    }

    @Test
    void testAdminRoleHasAllPermission()
    {
        assertTrue(
            policy.implies( new Role( "Admin" ), new AllPermission( "*" ) ),
            "Admin role should have AllPermission"
        );
    }

    @Test
    void testAllRoleHasViewPermission()
    {
        assertTrue(
            policy.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "All role should have view permission"
        );
    }

    @Test
    void testAllRoleLacksEditPermission()
    {
        assertFalse(
            policy.implies( Role.ALL, new PagePermission( "*:*", "edit" ) ),
            "All role should NOT have edit permission (only granted view)"
        );
    }

    @Test
    void testAuthenticatedHasCreatePages()
    {
        assertTrue(
            policy.implies( Role.AUTHENTICATED, new WikiPermission( "*", "createPages" ) ),
            "Authenticated role should have createPages wiki permission"
        );
    }

    @Test
    void testRefreshPicksUpChanges() throws Exception
    {
        // Initially, Anonymous does NOT have page edit
        assertFalse(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "edit" ) ),
            "Anonymous should not have edit before refresh"
        );

        // Insert a new grant directly via SQL
        try( final Connection conn = ds.getConnection();
             final Statement stmt = conn.createStatement() )
        {
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Anonymous', 'page', '*', 'edit')"
            );
        }

        // Before refresh, the cached policy should still say false
        assertFalse(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "edit" ) ),
            "Anonymous should not have edit before refresh is called"
        );

        // After refresh, the new grant should be picked up
        policy.refresh();
        assertTrue(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "edit" ) ),
            "Anonymous should have edit after refresh picks up the new grant"
        );
    }

    // ---- Error handling tests ----

    /**
     * When refresh() fails due to a database error (e.g., DB is down), the previously
     * loaded grants should be retained. This ensures the system keeps working with
     * stale data rather than losing all permissions.
     */
    @Test
    void testRefreshWithDatabaseDownKeepsStaleGrants() throws Exception
    {
        // Verify initial grants are loaded
        assertTrue(
            policy.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "All role should have view permission before DB failure"
        );

        // Create a DataSource that throws on getConnection() (simulating DB down)
        final DataSource failingDs = org.mockito.Mockito.mock( DataSource.class );
        org.mockito.Mockito.when( failingDs.getConnection() ).thenThrow(
            new java.sql.SQLException( "Connection refused - simulated DB failure" )
        );

        // Create a policy with normal data, then swap to failing DataSource via a new policy
        // that starts with the same data but then fails on refresh
        final DatabasePolicy policyWithFailure = new DatabasePolicy( ds, "policy_grants" );
        assertTrue(
            policyWithFailure.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "Should have grants after initial load"
        );

        // Now attempt refresh with a new policy backed by failing DS.
        // The refresh should log an error but keep the old grants from the successful constructor.
        final DatabasePolicy failPolicy = new DatabasePolicy( failingDs, "policy_grants" );
        // Constructor calls refresh() which will fail -- grants should be empty since there
        // were no previously loaded grants for this instance.
        assertFalse(
            failPolicy.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "Policy created with failing DB should have no grants"
        );

        // But the original policy should still work fine
        assertTrue(
            policy.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "Original policy should still have its grants"
        );
    }

    /**
     * When no grants are loaded (empty database table), implies() should return false
     * for all permission checks, effectively denying everything.
     */
    @Test
    void testImpliesWithEmptyGrantsReturnsFalse() throws Exception
    {
        // Clear all grants
        try( final Connection conn = ds.getConnection();
             final Statement stmt = conn.createStatement() )
        {
            stmt.executeUpdate( "DELETE FROM policy_grants" );
        }

        // Create a fresh policy from the now-empty table
        final DatabasePolicy emptyPolicy = new DatabasePolicy( ds, "policy_grants" );

        assertFalse(
            emptyPolicy.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "Empty grants should deny All role view permission"
        );
        assertFalse(
            emptyPolicy.implies( Role.AUTHENTICATED, new PagePermission( "*:*", "modify" ) ),
            "Empty grants should deny Authenticated role modify permission"
        );
        assertFalse(
            emptyPolicy.implies( new Role( "Admin" ), new AllPermission( "*" ) ),
            "Empty grants should deny Admin role AllPermission"
        );
    }

    // ---- Bootstrap admin override tests (at DefaultAuthorizationManager level) ----

    @Test
    void testBootstrapAdminNotTriggeredForGuest() throws Exception
    {
        // A guest session should NOT get bootstrap override
        final Properties props = TestEngine.getTestProperties();
        props.setProperty( "wikantik.admin.bootstrap", "admin" );
        final TestEngine engine = new TestEngine( props );
        final AuthorizationManager authMgr = engine.getManager( AuthorizationManager.class );
        final Session guestSession = engine.guestSession();
        // Guest's principal is "Guest", not "admin"
        assertFalse( authMgr.checkPermission( guestSession, new AllPermission( "*" ) ),
                "Guest should not receive bootstrap override" );
        engine.stop();
    }

    @Test
    void testBootstrapInactiveWhenNotConfigured() throws Exception
    {
        final Properties props = TestEngine.getTestProperties();
        // Don't set wikantik.admin.bootstrap
        final TestEngine engine = new TestEngine( props );
        final AuthorizationManager authMgr = engine.getManager( AuthorizationManager.class );
        final Session guestSession = engine.guestSession();
        assertFalse( authMgr.checkPermission( guestSession, new AllPermission( "*" ) ) );
        engine.stop();
    }

    /**
     * Verifies that when {@code wikantik.admin.bootstrap} is set in properties,
     * the DefaultAuthorizationManager stores the configured bootstrap admin name.
     * Uses reflection to verify the field since JAAS authentication is not available
     * in the test module.
     */
    @Test
    void testBootstrapPropertyIsReadDuringInitialization() throws Exception
    {
        final Properties props = TestEngine.getTestProperties();
        props.setProperty( "wikantik.admin.bootstrap", "testadmin" );
        final TestEngine engine = new TestEngine( props );
        final AuthorizationManager authMgr = engine.getManager( AuthorizationManager.class );

        // Use reflection to verify the private field
        final java.lang.reflect.Field field =
                DefaultAuthorizationManager.class.getDeclaredField( "bootstrapAdmin" );
        field.setAccessible( true );
        final String bootstrapAdmin = (String) field.get( authMgr );

        assertEquals( "testadmin", bootstrapAdmin,
                "bootstrapAdmin field should equal the configured property value" );
        engine.stop();
    }

    /**
     * Verifies that a blank bootstrap admin property is normalized to null.
     */
    @Test
    void testBootstrapBlankPropertyIsNormalized() throws Exception
    {
        final Properties props = TestEngine.getTestProperties();
        props.setProperty( "wikantik.admin.bootstrap", "   " );
        final TestEngine engine = new TestEngine( props );
        final AuthorizationManager authMgr = engine.getManager( AuthorizationManager.class );

        final java.lang.reflect.Field field =
                DefaultAuthorizationManager.class.getDeclaredField( "bootstrapAdmin" );
        field.setAccessible( true );
        final String bootstrapAdmin = (String) field.get( authMgr );

        assertNull( bootstrapAdmin,
                "Blank bootstrap admin property should be normalized to null" );
        engine.stop();
    }
}
