/*
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
 */
package com.wikantik.auth;

import com.wikantik.HsqlDbUtils;
import com.wikantik.TestJDBCDataSource;
import com.wikantik.TestJNDIContext;
import com.wikantik.auth.authorize.Role;
import com.wikantik.auth.permissions.AllPermission;
import com.wikantik.auth.permissions.PagePermission;
import com.wikantik.auth.permissions.WikiPermission;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NameAlreadyBoundException;
import javax.sql.DataSource;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for {@link DatabasePolicy}, which loads policy grants from the
 * {@code policy_grants} database table and provides an
 * {@code implies(Principal, Permission)} method.
 */
@TestInstance( TestInstance.Lifecycle.PER_CLASS )
class DatabasePolicyTest
{
    private final HsqlDbUtils hu = new HsqlDbUtils();
    private DataSource ds;
    private DatabasePolicy policy;

    @BeforeAll
    void startDatabase() throws Exception
    {
        hu.setUp();

        // Set up the mock JNDI initial context
        TestJNDIContext.initialize();
        final Context initCtx = new InitialContext();
        try
        {
            initCtx.bind( "java:comp/env", new TestJNDIContext() );
        }
        catch( final NameAlreadyBoundException e )
        {
            // ignore -- already bound by another test
        }
        final Context ctx = (Context) initCtx.lookup( "java:comp/env" );
        ds = new TestJDBCDataSource( new File( "target/test-classes/wikantik-custom.properties" ), hu.getDriverUrl() );
        ctx.bind( "jdbc/PolicyDatabase", ds );

        // Create policy_grants table using admin connection (SA user has DDL privileges)
        try( final Connection adminConn = DriverManager.getConnection( hu.getDriverUrl(), "SA", "" );
             final Statement stmt = adminConn.createStatement() )
        {
            stmt.executeUpdate(
                "CREATE TABLE IF NOT EXISTS policy_grants (" +
                "  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  principal_type VARCHAR(10) NOT NULL," +
                "  principal_name VARCHAR(255) NOT NULL," +
                "  permission_type VARCHAR(10) NOT NULL," +
                "  target VARCHAR(255) NOT NULL," +
                "  actions VARCHAR(255) NOT NULL" +
                ")"
            );
            stmt.executeUpdate( "GRANT SELECT, INSERT, UPDATE, DELETE ON policy_grants TO \"wikantik\"" );
        }
    }

    @BeforeEach
    void setUp() throws Exception
    {
        try( final Connection conn = ds.getConnection();
             final Statement stmt = conn.createStatement() )
        {
            // Reset data using DML (the wikantik user has DML privileges)
            stmt.executeUpdate( "DELETE FROM policy_grants" );

            // Seed data matching the default wiki policy
            // All role: view only
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'All', 'page', '*', 'view')"
            );
            // Anonymous role: login, editProfile
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Anonymous', 'wiki', '*', 'login,editProfile')"
            );
            // Authenticated role: page modify,rename
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Authenticated', 'page', '*', 'modify,rename')"
            );
            // Authenticated role: wiki createPages,createGroups
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Authenticated', 'wiki', '*', 'createPages,createGroups')"
            );
            // Authenticated role: group edit on <groupmember>
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Authenticated', 'group', '*:<groupmember>', 'edit')"
            );
            // Admin role: AllPermission (actions = '*')
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Admin', 'page', '*', '*')"
            );
        }

        // Create a fresh policy instance that reads from the seeded table
        policy = new DatabasePolicy( ds, "policy_grants" );
    }

    @AfterAll
    void stopDatabase()
    {
        hu.tearDown();
    }

    // ---- Test methods ----

    @Test
    void testAuthenticatedRoleHasModifyPermission()
    {
        assertTrue(
            policy.implies( Role.AUTHENTICATED, new PagePermission( "*:*", "modify" ) ),
            "Authenticated role should have modify permission on all pages"
        );
    }

    @Test
    void testAuthenticatedRoleHasViewViaImplication()
    {
        // modify implies view (modify -> edit -> view)
        assertTrue(
            policy.implies( Role.AUTHENTICATED, new PagePermission( "*:*", "view" ) ),
            "Authenticated role should have view permission via modify implication"
        );
    }

    @Test
    void testAnonymousRoleLacksDeletePermission()
    {
        assertFalse(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "delete" ) ),
            "Anonymous role should NOT have delete permission"
        );
    }

    @Test
    void testAdminRoleHasAllPermission()
    {
        assertTrue(
            policy.implies( new Role( "Admin" ), new AllPermission( "*" ) ),
            "Admin role should have AllPermission"
        );
    }

    @Test
    void testAllRoleHasViewPermission()
    {
        assertTrue(
            policy.implies( Role.ALL, new PagePermission( "*:*", "view" ) ),
            "All role should have view permission"
        );
    }

    @Test
    void testAllRoleLacksEditPermission()
    {
        assertFalse(
            policy.implies( Role.ALL, new PagePermission( "*:*", "edit" ) ),
            "All role should NOT have edit permission (only granted view)"
        );
    }

    @Test
    void testAuthenticatedHasCreatePages()
    {
        assertTrue(
            policy.implies( Role.AUTHENTICATED, new WikiPermission( "*", "createPages" ) ),
            "Authenticated role should have createPages wiki permission"
        );
    }

    @Test
    void testRefreshPicksUpChanges() throws Exception
    {
        // Initially, Anonymous does NOT have page edit
        assertFalse(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "edit" ) ),
            "Anonymous should not have edit before refresh"
        );

        // Insert a new grant directly via SQL
        try( final Connection conn = ds.getConnection();
             final Statement stmt = conn.createStatement() )
        {
            stmt.executeUpdate(
                "INSERT INTO policy_grants (principal_type, principal_name, permission_type, target, actions) " +
                "VALUES ('role', 'Anonymous', 'page', '*', 'edit')"
            );
        }

        // Before refresh, the cached policy should still say false
        assertFalse(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "edit" ) ),
            "Anonymous should not have edit before refresh is called"
        );

        // After refresh, the new grant should be picked up
        policy.refresh();
        assertTrue(
            policy.implies( Role.ANONYMOUS, new PagePermission( "*:*", "edit" ) ),
            "Anonymous should have edit after refresh picks up the new grant"
        );
    }
}
