#!/bin/bash
#
# entrypoint.sh — container runtime bootstrap. Materialises
# wikantik-custom.properties from the surrounding env, runs DB migrations
# (idempotent via schema_migrations), optionally seeds dev users, then
# exec's Catalina to start Tomcat.
#
# This file is not run interactively in normal use — it's the
# Dockerfile's CMD. It is included in the image at /opt/wikantik/entrypoint.sh
# and invoked with whatever arguments the operator passes to the
# container (default: catalina.sh run).
#
# Usage:
#   entrypoint.sh             # bootstrap + start Tomcat in foreground
#   entrypoint.sh --help      # show this help
#   entrypoint.sh /bin/sh     # bypass Tomcat (passes through to exec)
#
# Environment variables:
#   POSTGRES_HOST                PG host (required)
#   POSTGRES_PORT                PG port (default 5432)
#   POSTGRES_DB                  PG database (required)
#   POSTGRES_USER                PG application user (required)
#   POSTGRES_PASSWORD            PG application password (required)
#   WIKANTIK_BASE_URL            external base URL (default http://localhost:8080/)
#   WIKANTIK_PAGE_DIR            page tree mount (default /var/wikantik/pages)
#   WIKANTIK_WORK_DIR            scratch dir (default /var/wikantik/work)
#   WIKANTIK_ATTACHMENT_DIR      attachments dir (default /var/wikantik/pages)
#   WIKANTIK_SEED_DEV_USERS      "true" to insert admin/admin123 + testbot
#                                via bin/db/seed-users.sql (dev only)
#   WIKANTIK_DENSE_BACKEND       dense retrieval backend override:
#                                  inmemory | pgvector | lucene-hnsw (default: ini bundle default = inmemory)
#   WIKANTIK_DENSE_EF_SEARCH     pgvector HNSW ef_search knob (default 100; only used when
#                                WIKANTIK_DENSE_BACKEND=pgvector). The lucene-hnsw backend's
#                                knobs (m / ef_construction / ef_search) use HnswParams defaults
#                                unless set via wikantik.search.dense.lucene.* properties.
#   WIKANTIK_LUCENE_DIRECTORY    Lucene Directory backend: nio | mmap (default: nio)
#   WIKANTIK_VERSIONING_CACHE_SIZE
#                                VersioningFileProvider property cache size (default 100;
#                                set 0 for single-entry, -1 to disable; properties are
#                                tiny so a few thousand entries is cheap)
#   WIKANTIK_MAX_INFLIGHT_REQUESTS
#                                BackpressureFilter permit cap (default 390, which must
#                                stay below Tomcat maxThreads=400; 0 or negative disables
#                                backpressure entirely). Requests over the cap get HTTP
#                                503 + Retry-After:1 instead of queueing for up to 60 s.
#                                /api/health and /metrics bypass.
#                                Metric: wikantik_backpressure.rejected_total
#   WIKANTIK_COOKIE_AUTHENTICATION  "true" to enable remember-me re-auth so users
#                                stay logged in across restarts/timeouts (default false)
#   WIKANTIK_SSO_ENABLED         "true" to enable Single Sign-On (default off)
#   WIKANTIK_SSO_TYPE            oidc | saml | both (default oidc)
#   WIKANTIK_SSO_OIDC_DISCOVERY_URI  provider OIDC discovery doc URL
#   WIKANTIK_SSO_OIDC_CLIENT_ID  OAuth client id
#   WIKANTIK_SSO_OIDC_CLIENT_SECRET  OAuth client secret (sensitive)
#   WIKANTIK_SSO_OIDC_SCOPE      OAuth scope (default "openid profile email")
#   WIKANTIK_SSO_IDENTITY_CLAIM  identity claim (default "sub")
#   WIKANTIK_SSO_AUTO_PROVISION  "true" to auto-create profiles (default true)
#   WIKANTIK_SSO_CLAIM_LOGIN_NAME IdP claim mapped to wiki login name
#                                (default preferred_username; Google sends none,
#                                so set to "email" for Google)
#   WIKANTIK_SSO_CLAIM_FULL_NAME IdP claim mapped to display name (default "name")
#   WIKANTIK_SSO_CLAIM_EMAIL     IdP claim mapped to email (default "email")
#                                redirect_uri = WIKANTIK_BASE_URL + /sso/callback
#   CATALINA_HOME                tomcat root (default /usr/local/tomcat)

set -euo pipefail

case "${1:-}" in
    -h|--help)
        awk '/^#!/{next} !/^#/{exit} {sub(/^# ?/,""); print}' "$0"
        exit 0
        ;;
esac

CATALINA_HOME="${CATALINA_HOME:-/usr/local/tomcat}"

# --- Generate wikantik-custom.properties ---
cat > "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF
# Auto-generated by entrypoint.sh — do not edit manually

wikantik.applicationName = Wikantik
wikantik.use.external.logconfig = true
wikantik.pageProvider = VersioningFileProvider
wikantik.frontPage = Main

wikantik.baseURL = ${WIKANTIK_BASE_URL:-http://localhost:8080/}

wikantik.fileSystemProvider.pageDir = ${WIKANTIK_PAGE_DIR:-/var/wikantik/pages}
wikantik.workDir = ${WIKANTIK_WORK_DIR:-/var/wikantik/work}
wikantik.basicAttachmentProvider.storageDir = ${WIKANTIK_ATTACHMENT_DIR:-/var/wikantik/pages}

wikantik.cache.allPagesTTL = 60

# Remember-me: when true, a successful password login issues a Lax, httpOnly,
# scheme-Secure remember-me cookie so a request silently re-authenticates after
# the server session is gone (restart/redeploy/timeout) instead of logging the
# user out. Default off (conservative).
wikantik.cookieAuthentication = ${WIKANTIK_COOKIE_AUTHENTICATION:-false}

# PostgreSQL JDBC user/group database — single shared DataSource named
# jdbc/WikiDatabase. Matches the canonical bare-metal template; the app
# reads the wikantik.datasource property and binds JDBCUserDatabase + JDBCGroupDatabase
# to that one resource.
wikantik.userdatabase = com.wikantik.auth.user.JDBCUserDatabase
wikantik.groupdatabase = com.wikantik.auth.authorize.JDBCGroupDatabase
wikantik.datasource = jdbc/WikiDatabase

wikantik.userdatabase.table = users
wikantik.userdatabase.uid = uid
wikantik.userdatabase.email = email
wikantik.userdatabase.fullName = full_name
wikantik.userdatabase.loginName = login_name
wikantik.userdatabase.password = password
wikantik.userdatabase.wikiName = wiki_name
wikantik.userdatabase.created = created
wikantik.userdatabase.modified = modified
wikantik.userdatabase.lockExpiry = lock_expiry
wikantik.userdatabase.attributes = attributes
wikantik.userdatabase.roleTable = roles
wikantik.userdatabase.role = role

wikantik.groupdatabase.table = groups
wikantik.groupdatabase.membertable = group_members
wikantik.groupdatabase.name = name
wikantik.groupdatabase.created = created
wikantik.groupdatabase.creator = creator
wikantik.groupdatabase.member = member
wikantik.groupdatabase.modified = modified
wikantik.groupdatabase.modifier = modifier
EOF

# Append SMTP config if host is set
if [ -n "${MAIL_SMTP_HOST:-}" ]; then
  cat >> "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF

# SMTP configuration
mail.smtp.host = ${MAIL_SMTP_HOST}
mail.smtp.port = ${MAIL_SMTP_PORT:-587}
mail.smtp.account = ${MAIL_SMTP_ACCOUNT:-}
mail.smtp.password = ${MAIL_SMTP_PASSWORD:-}
mail.smtp.starttls.enable = true
mail.from = ${MAIL_FROM:-wiki@localhost}
EOF
fi

# Optional: dense-retrieval backend override.
#   WIKANTIK_DENSE_BACKEND        — inmemory | pgvector | lucene-hnsw  (default from ini bundle: inmemory)
#   WIKANTIK_DENSE_EF_SEARCH      — pgvector HNSW recall/latency knob (default 100)
# When unset, the ini-bundle default (inmemory) wins. Setting pgvector
# requires V032 applied + content_chunk_embeddings.embedding populated
# (run bin/db/one-shots/2026-05-20-backfill-chunk-embeddings.sh first).
if [ -n "${WIKANTIK_DENSE_BACKEND:-}" ]; then
  cat >> "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF

# Dense retrieval backend override (entrypoint-injected from env).
wikantik.search.dense.backend            = ${WIKANTIK_DENSE_BACKEND}
wikantik.search.dense.pgvector.ef_search = ${WIKANTIK_DENSE_EF_SEARCH:-100}
EOF
fi

# Optional: Lucene Directory backend override.
#   WIKANTIK_LUCENE_DIRECTORY    — nio | mmap  (default from ini bundle: nio)
# 'mmap' is Lucene's recommended default on 64-bit Linux; flip in .env and
# `bin/remote.sh deploy --skip-build` to restart with the new backend. Rollback
# is the inverse flip + same fast restart.
if [ -n "${WIKANTIK_LUCENE_DIRECTORY:-}" ]; then
  cat >> "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF

# Lucene Directory backend override (entrypoint-injected from env).
wikantik.search.lucene.directory.kind = ${WIKANTIK_LUCENE_DIRECTORY}
EOF
fi

# Optional: VersioningFileProvider property cache size.
#   WIKANTIK_VERSIONING_CACHE_SIZE — int > 0, default 100 (per ini bundle).
# Properties files are tiny (~hundreds of bytes each), so a generous cap of a
# few thousand entries costs ~MBs of heap and is the right call for a busy
# read workload. Set to 0 to fall back to SingleEntryPropertyCache, -1 to
# disable property caching entirely.
if [ -n "${WIKANTIK_VERSIONING_CACHE_SIZE:-}" ]; then
  cat >> "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF

# VersioningFileProvider property cache size (entrypoint-injected from env).
wikantik.versioningFileProvider.cacheSize = ${WIKANTIK_VERSIONING_CACHE_SIZE}
EOF
fi

# Optional: Single Sign-On (OIDC/SAML via pac4j).
#   WIKANTIK_SSO_ENABLED            "true" to turn SSO on (default off; block skipped when unset/false).
#   WIKANTIK_SSO_TYPE               oidc | saml | both (default oidc).
#   WIKANTIK_SSO_OIDC_DISCOVERY_URI provider OIDC discovery doc, e.g.
#                                   https://accounts.google.com/.well-known/openid-configuration
#   WIKANTIK_SSO_OIDC_CLIENT_ID     OAuth client id from the provider console.
#   WIKANTIK_SSO_OIDC_CLIENT_SECRET OAuth client secret (sensitive — keep in .env.prod, never in git).
#   WIKANTIK_SSO_OIDC_SCOPE         optional; default "openid profile email".
#   WIKANTIK_SSO_IDENTITY_CLAIM     optional; default "sub" (immutable subject). Set to
#                                   preferred_username only to deliberately trust a mutable claim.
#   WIKANTIK_SSO_AUTO_PROVISION     optional; default "true" (create a local profile on first login).
# The OAuth redirect_uri is derived as wikantik.baseURL + /sso/callback, so
# WIKANTIK_BASE_URL must be the public https origin registered with the provider.
if [ "${WIKANTIK_SSO_ENABLED:-false}" = "true" ]; then
  cat >> "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF

# Single Sign-On (entrypoint-injected from env).
wikantik.sso.enabled = true
wikantik.sso.type = ${WIKANTIK_SSO_TYPE:-oidc}
wikantik.sso.oidc.discoveryUri = ${WIKANTIK_SSO_OIDC_DISCOVERY_URI:-}
wikantik.sso.oidc.clientId = ${WIKANTIK_SSO_OIDC_CLIENT_ID:-}
wikantik.sso.oidc.clientSecret = ${WIKANTIK_SSO_OIDC_CLIENT_SECRET:-}
wikantik.sso.oidc.scope = ${WIKANTIK_SSO_OIDC_SCOPE:-openid profile email}
wikantik.sso.identityClaim = ${WIKANTIK_SSO_IDENTITY_CLAIM:-sub}
wikantik.sso.autoProvision = ${WIKANTIK_SSO_AUTO_PROVISION:-true}
wikantik.sso.claimMapping.loginName = ${WIKANTIK_SSO_CLAIM_LOGIN_NAME:-preferred_username}
wikantik.sso.claimMapping.fullName = ${WIKANTIK_SSO_CLAIM_FULL_NAME:-name}
wikantik.sso.claimMapping.email = ${WIKANTIK_SSO_CLAIM_EMAIL:-email}
EOF
fi

# --- Generate ROOT.xml (Tomcat context with JNDI DataSources) ---
POSTGRES_HOST="${POSTGRES_HOST:-db}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_DB="${POSTGRES_DB:-wikantik}"
POSTGRES_USER="${POSTGRES_USER:-wikantik}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-CHANGEME}"

JDBC_URL="jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

mkdir -p "${CATALINA_HOME}/conf/Catalina/localhost"
cat > "${CATALINA_HOME}/conf/Catalina/localhost/ROOT.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<Context reloadable="false" cachingAllowed="true">

    <!-- Single shared DataSource. App looks up jdbc/WikiDatabase via the
         wikantik.datasource property; both JDBCUserDatabase and
         JDBCGroupDatabase bind to this one connection pool. Matches the
         shape of the bare-metal Wikantik-context.xml.template so the two
         install paths use identical JNDI conventions. -->
    <Resource name="jdbc/WikiDatabase"
              auth="Container"
              type="javax.sql.DataSource"
              factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory"
              driverClassName="org.postgresql.Driver"
              url="${JDBC_URL}"
              username="${POSTGRES_USER}"
              password="${POSTGRES_PASSWORD}"
              maxTotal="90"
              maxIdle="30"
              maxWaitMillis="5000"
              validationQuery="SELECT 1"
              testOnBorrow="false"
              testWhileIdle="true"
              timeBetweenEvictionRunsMillis="30000"/>

</Context>
EOF

# --- Generate wikantik-mcp.properties ---
cat > "${CATALINA_HOME}/lib/wikantik-mcp.properties" <<EOF
mcp.server.name = wikantik-mcp
mcp.server.title = Wikantik Knowledge Base
mcp.server.version = 2.0.0
mcp.instructions.file = wikantik-mcp-instructions.txt
mcp.ratelimit.global = ${MCP_RATE_LIMIT_GLOBAL:-100}
mcp.ratelimit.perClient = ${MCP_RATE_LIMIT_PER_CLIENT:-10}
EOF

if [ -n "${MCP_ACCESS_KEYS:-}" ]; then
  echo "mcp.access.keys = ${MCP_ACCESS_KEYS}" >> "${CATALINA_HOME}/lib/wikantik-mcp.properties"
fi

# --- Dev mode: deploy bind-mounted WAR if present ---
if [ -f /tmp/Wikantik.war ]; then
  echo "Dev mode: deploying /tmp/Wikantik.war"
  rm -rf "${CATALINA_HOME}/webapps/ROOT"
  mkdir -p "${CATALINA_HOME}/webapps/ROOT"
  unzip -q -o -d "${CATALINA_HOME}/webapps/ROOT" /tmp/Wikantik.war
fi

# --- Apply DB migrations ---
# Idempotent: schema_migrations table tracks applied versions so re-runs
# only execute new ones. Failure exits non-zero — Tomcat never starts
# against an out-of-date schema. Same script + migrations/ that the
# bare-metal install and CI both use.
if [ -x /opt/wikantik/db/migrate.sh ]; then
  echo "Running database migrations..."
  DB_NAME="${POSTGRES_DB}" \
  DB_APP_USER="${POSTGRES_USER}" \
  PGHOST="${POSTGRES_HOST}" \
  PGPORT="${POSTGRES_PORT}" \
  PGUSER="${POSTGRES_USER}" \
  PGPASSWORD="${POSTGRES_PASSWORD}" \
    /opt/wikantik/db/migrate.sh
fi

# --- Optional dev-user seeding ---
# seed-users.sql installs admin/admin123 and a basic user account with
# known dev-only passwords. Off by default (production deploys must NOT
# inherit known credentials); the bare-metal deploy script + the test
# stack opt in via WIKANTIK_SEED_DEV_USERS=true.
if [ "${WIKANTIK_SEED_DEV_USERS:-false}" = "true" ] && [ -f /opt/wikantik/db/seed-users.sql ]; then
  echo "Seeding dev user accounts (admin/admin123)..."
  PGHOST="${POSTGRES_HOST}" PGPORT="${POSTGRES_PORT}" \
  PGUSER="${POSTGRES_USER}" PGPASSWORD="${POSTGRES_PASSWORD}" \
    psql -d "${POSTGRES_DB}" -f /opt/wikantik/db/seed-users.sql -q || \
    echo "WARN: seed-users.sql failed; check /opt/wikantik/db/seed-users.sql"
fi

exec "$@"
