#!/bin/bash
set -euo pipefail

CATALINA_HOME="${CATALINA_HOME:-/usr/local/tomcat}"

# --- Generate wikantik-custom.properties ---
cat > "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF
# Auto-generated by entrypoint.sh — do not edit manually

wikantik.applicationName = Wikantik
wikantik.use.external.logconfig = true
wikantik.pageProvider = FileSystemProvider
wikantik.frontPage = Main

wikantik.baseURL = ${WIKANTIK_BASE_URL:-http://localhost:8080/}

wikantik.fileSystemProvider.pageDir = ${WIKANTIK_PAGE_DIR:-/var/wikantik/pages}
wikantik.workDir = ${WIKANTIK_WORK_DIR:-/var/wikantik/work}
wikantik.basicAttachmentProvider.storageDir = ${WIKANTIK_ATTACHMENT_DIR:-/var/wikantik/pages}

wikantik.cache.allPagesTTL = 60

# PostgreSQL JDBC user/group database
wikantik.userdatabase = com.wikantik.auth.user.JDBCUserDatabase
wikantik.groupdatabase = com.wikantik.auth.authorize.JDBCGroupDatabase

wikantik.userdatabase.datasource = jdbc/UserDatabase
wikantik.groupdatabase.datasource = jdbc/GroupDatabase

wikantik.userdatabase.table = users
wikantik.userdatabase.uid = uid
wikantik.userdatabase.email = email
wikantik.userdatabase.fullName = full_name
wikantik.userdatabase.loginName = login_name
wikantik.userdatabase.password = password
wikantik.userdatabase.wikiName = wiki_name
wikantik.userdatabase.created = created
wikantik.userdatabase.modified = modified
wikantik.userdatabase.lockExpiry = lock_expiry
wikantik.userdatabase.attributes = attributes
wikantik.userdatabase.roleTable = roles
wikantik.userdatabase.role = role

wikantik.groupdatabase.table = groups
wikantik.groupdatabase.membertable = group_members
wikantik.groupdatabase.name = name
wikantik.groupdatabase.created = created
wikantik.groupdatabase.creator = creator
wikantik.groupdatabase.member = member
wikantik.groupdatabase.modified = modified
wikantik.groupdatabase.modifier = modifier
EOF

# Append SMTP config if host is set
if [ -n "${MAIL_SMTP_HOST:-}" ]; then
  cat >> "${CATALINA_HOME}/lib/wikantik-custom.properties" <<EOF

# SMTP configuration
mail.smtp.host = ${MAIL_SMTP_HOST}
mail.smtp.port = ${MAIL_SMTP_PORT:-587}
mail.smtp.account = ${MAIL_SMTP_ACCOUNT:-}
mail.smtp.password = ${MAIL_SMTP_PASSWORD:-}
mail.smtp.starttls.enable = true
mail.from = ${MAIL_FROM:-wiki@localhost}
EOF
fi

# --- Generate ROOT.xml (Tomcat context with JNDI DataSources) ---
POSTGRES_HOST="${POSTGRES_HOST:-db}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_DB="${POSTGRES_DB:-wikantik}"
POSTGRES_USER="${POSTGRES_USER:-wikantik}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-CHANGEME}"

JDBC_URL="jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

mkdir -p "${CATALINA_HOME}/conf/Catalina/localhost"
cat > "${CATALINA_HOME}/conf/Catalina/localhost/ROOT.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<Context reloadable="false" cachingAllowed="true">

    <Resource name="jdbc/UserDatabase"
              auth="Container"
              type="javax.sql.DataSource"
              factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory"
              driverClassName="org.postgresql.Driver"
              url="${JDBC_URL}"
              username="${POSTGRES_USER}"
              password="${POSTGRES_PASSWORD}"
              maxTotal="20"
              maxIdle="10"
              maxWaitMillis="10000"
              validationQuery="SELECT 1"
              testOnBorrow="true"/>

    <Resource name="jdbc/GroupDatabase"
              auth="Container"
              type="javax.sql.DataSource"
              factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory"
              driverClassName="org.postgresql.Driver"
              url="${JDBC_URL}"
              username="${POSTGRES_USER}"
              password="${POSTGRES_PASSWORD}"
              maxTotal="20"
              maxIdle="10"
              maxWaitMillis="10000"
              validationQuery="SELECT 1"
              testOnBorrow="true"/>

</Context>
EOF

# --- Generate wikantik-mcp.properties ---
cat > "${CATALINA_HOME}/lib/wikantik-mcp.properties" <<EOF
mcp.server.name = wikantik-mcp
mcp.server.title = Wikantik Knowledge Base
mcp.server.version = 2.0.0
mcp.instructions.file = wikantik-mcp-instructions.txt
mcp.ratelimit.global = ${MCP_RATE_LIMIT_GLOBAL:-100}
mcp.ratelimit.perClient = ${MCP_RATE_LIMIT_PER_CLIENT:-10}
EOF

if [ -n "${MCP_ACCESS_KEYS:-}" ]; then
  echo "mcp.access.keys = ${MCP_ACCESS_KEYS}" >> "${CATALINA_HOME}/lib/wikantik-mcp.properties"
fi

# --- Dev mode: deploy bind-mounted WAR if present ---
if [ -f /tmp/Wikantik.war ]; then
  echo "Dev mode: deploying /tmp/Wikantik.war"
  rm -rf "${CATALINA_HOME}/webapps/ROOT"
  mkdir -p "${CATALINA_HOME}/webapps/ROOT"
  unzip -q -o -d "${CATALINA_HOME}/webapps/ROOT" /tmp/Wikantik.war
fi

exec "$@"
