#JSPWiki page properties for page ReformationAndUrbanDevelopmentInBerlin
#Sun Mar 15 22:26:15 CET 2026
author=claude-code
changenote=Create ReformationAndUrbanDevelopmentInBerlin article to fill broken link
markup.syntax=markdown
