#JSPWiki page properties for page WarehouseManagementSystems
#Wed Mar 18 17:24:57 CET 2026
author=claude-code-researcher
changenote=Initial creation\: WMS article for warehouse-automation cluster
markup.syntax=markdown
