import { useState } from 'react';
import { api } from '../../api/client';
import ProposalReviewQueue from './ProposalReviewQueue';
import GraphExplorer from './GraphExplorer';
import EdgeExplorer from './EdgeExplorer';
import KgEmbeddingsTab from './KgEmbeddingsTab';
import ContentEmbeddingsTab from './ContentEmbeddingsTab';
import HubProposalsTab from './HubProposalsTab';
import HubDiscoveryTab from './HubDiscoveryTab';
import '../../styles/admin.css';

const TABS = [
  { id: 'proposals', label: 'Proposals',
    description: 'Review pending knowledge graph proposals generated by page analysis. Each proposal suggests a new node or edge with a confidence score and reasoning. Approve or reject proposals individually to curate the graph.' },
  { id: 'node-explorer', label: 'Node Explorer',
    description: 'Browse, search, and inspect all nodes in the knowledge graph. Filter by node type or status, view detailed properties for any node, and project page frontmatter into the graph to keep nodes in sync with wiki content.' },
  { id: 'edge-explorer', label: 'Edge Explorer',
    description: 'Browse and search all edges (relationships) in the knowledge graph. Filter by relationship type, inspect how nodes are connected, and review provenance information showing where each edge originated.' },
  { id: 'kg-embeddings', label: 'KG Embeddings',
    description: 'Train and manage the knowledge graph embedding model that learns vector representations of entities and relationship types. Once trained, view predicted missing edges, flag low-plausibility edges for review, and identify merge candidates where structurally similar nodes may represent the same concept.' },
  { id: 'content-embeddings', label: 'Content Embeddings',
    description: 'Train and manage the content embedding model that computes page similarity from text. Identify pages missing frontmatter and bulk-backfill it, and review the most similar page pairs to spot duplicates or candidates for cross-linking.' },
  { id: 'hub-proposals', label: 'Hub Proposals',
    description: 'Generate and manage hub membership proposals that suggest which pages belong to topic hubs based on content similarity. Approve or reject proposals individually, in bulk, or by setting a percentile threshold to auto-approve the strongest matches.' },
  { id: 'hub-discovery', label: 'Hub Discovery',
    description: 'Run cluster-based discovery to find new topic hubs across the wiki. Review discovered clusters as proposal cards, accept promising hubs, dismiss irrelevant ones, and manage existing hub memberships. Previously dismissed proposals are tracked to avoid rediscovery.' },
];

export default function AdminKnowledgePage() {
  const [activeTab, setActiveTab] = useState('proposals');
  const [clearing, setClearing] = useState(false);

  const handleClearAll = async () => {
    if (!confirm('Delete ALL knowledge graph data? This removes all nodes, edges, proposals, and embeddings.')) return;
    setClearing(true);
    try {
      await api.knowledge.clearAll();
      window.location.reload();
    } catch (err) {
      alert('Clear failed: ' + err.message);
    } finally {
      setClearing(false);
    }
  };

  return (
    <div className="admin-knowledge page-enter">
      <div className="admin-toolbar">
        <div className="admin-tabs">
          {TABS.map(tab => (
            <button
              key={tab.id}
              className={`admin-tab ${activeTab === tab.id ? 'active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <button
          className="btn btn-sm"
          style={{ marginLeft: 'auto', color: 'var(--danger)' }}
          onClick={handleClearAll}
          disabled={clearing}
        >
          {clearing ? 'Clearing...' : 'Clear All'}
        </button>
      </div>
      <p className="tab-description">
        {TABS.find(t => t.id === activeTab)?.description}
      </p>
      {activeTab === 'proposals' && <ProposalReviewQueue />}
      {activeTab === 'node-explorer' && <GraphExplorer />}
      {activeTab === 'edge-explorer' && <EdgeExplorer />}
      {activeTab === 'kg-embeddings' && <KgEmbeddingsTab />}
      {activeTab === 'content-embeddings' && <ContentEmbeddingsTab />}
      {activeTab === 'hub-proposals' && <HubProposalsTab />}
      {activeTab === 'hub-discovery' && <HubDiscoveryTab />}
    </div>
  );
}
